# https://baijiahao.baidu.com/s?id=1720756723697942215&wfr=spider&for=pc
version: "3"

# networks:
#   network:
#     ipam:
#       driver: default
#       config:
#         - subnet: '177.7.0.0/16'
networks:
  Wayneyao:

services:
  mysql:
    image: mysql:8.0.21
    container_name: wayneyao-mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci #设置utf8字符集
    restart: always #每次重启docker时都会重启相关的容器
    ports:
      - "13306:3306"  # host物理直接映射端口为13306
    environment:
      MYSQL_DATABASE: 'qmPlus' # 初始化启动时要创建的数据库的名称
      MYSQL_ROOT_PASSWORD: '123456' # root管理员用户密码
    networks:
      - Wayneyao
    # networks:
    #   network:
    #     ipv4_address: 177.7.0.13

  redis:
    image: redis:6.0.6
    container_name: wayneyao-redis # 容器名
    restart: always #每次重启docker时都会重启相关的容器
    ports:
      - '16379:6379'
    networks:
      - Wayneyao
    # networks:
    #   network:
    #     ipv4_address: 177.7.0.14