// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)


var doc2 = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/fabricClient/fabricPosttest": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "FabricClient"
                ],
                "summary": "posttest",
                "parameters": [
                    {
                        "description": "ID NAME AGE",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/fabric.posttest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"测试成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/fabricClient/fabricInit": {
            "post": {
                "tags": [
                    "FabricClient"
                ],
                "parameters": [
                    {
                        "description": "更新fabricSDK client",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/fabric.init"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"初始化成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/fabricClient/fabriccinstall": {
            "post": {
                "tags": [
                    "FabricClient"
                ],
                "parameters": [
                    {
                        "description": "更新fabricSDK client",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/fabric.ccinstall"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"初始化成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/fabricClient/fabriccexecute": {
            "post": {
                "tags": [
                    "FabricClient"
                ],
                "parameters": [
                    {
                        "description": "更新fabricSDK client",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/fabric.execute"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"初始化成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/fabricClient/getChannelList": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "FabricClient"
                ],
                "summary": "获取所有通道详细信息",
                "responses": {
                    "200": {
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"获取成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/fabricClient/getPeerList": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "FabricClient"
                ],
                "summary": "获取所有通道",
                "responses": {
                    "200": {
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"获取成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/fabricClient/getInstalledCC": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "FabricClient"
                ],
                "summary": "获取所有区块",
                "responses": {
                    "200": {
                        "description": "{\"success\":true,\"data\":{},\"msg\":\"获取成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
    },
    
    "definitions": {
        "fabric.posttest": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "号码",
                    "type": "string"
                },
                "name": {
                    "description": "姓名",
                    "type": "string"
                },
                "age": {
                    "description": "年纪",
                    "type": "string"
                }
            }
        },
        "fabric.init": {
            "type": "object",
            "properties": {
                "configPath": {
                    "description": "验证码",
                    "type": "string"
                },
                "channelID": {
                    "description": "验证码ID",
                    "type": "string"
                },
                "username": {
                    "description": "密码",
                    "type": "string"
                },
                "org": {
                    "description": "用户名",
                    "type": "string"
                }
            }
        },
        "fabric.execute": {
            "type": "object",
            "properties": {
                "name": {
                    "description": "链码名称",
                    "type": "string"
                },
                "func": {
                    "description": "调用函数",
                    "type": "string"
                },
                "args": {
                    "description": "参数",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
            }
        },
        "fabric.ccinstall": {
            "type": "object",
            "properties": {
                "name": {
                    "description": "链码名称",
                    "type": "string"
                },
                "version": {
                    "description": "版本号",
                    "type": "string"
                },
                "sequence": {
                    "description": "序列号 每次更新都得手动加一",
                    "type": "string"
                },
                "channel": {
                    "description": "验证码ID",
                    "type": "string"
                },
                "path": {
                    "description": "密码",
                    "type": "string"
                },
                "org": {
                    "description": "组织名称",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "user": {
                    "description": "用户",
                    "type": "string"
                },
                "cclang": {
                    "description": "智能合约使用语言",
                    "type": "string"
                },
                "ccpolicy": {
                    "description": "签名策略",
                    "type": "string"
                },
                "Initreq": {
                    "description": "签名策略",
                    "type": "string"
                },
            }
        },
    },

    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "x-token",
            "in": "header"
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "0.0.1",
	Host:        "",
	BasePath:    "/",
	Schemes:     []string{},
	Title:       "Swagger Example API",
	Description: "fabric chaincode server pets",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc2)
	if err != nil {
		return doc2
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc2
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
