version: 1.0.0

channels:
  mychannel:
    peers:
      peer0.org1.ca.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
    orderers:
      - orderer1.ca.com
  # channel1:
  #   peers:
  #     peer0.org1.ca.com:
  #       endorsingPeer: true
  #       chaincodeQuery: true
  #       ledgerQuery: true
  #       eventSource: true
  #   orderers:
  #     - orderer1.ca.com
  # channel2:
  #   peers:
  #     peer0.org1.ca.com:
  #       endorsingPeer: true
  #       chaincodeQuery: true
  #       ledgerQuery: true
  #       eventSource: true
  #   orderers:
  #     - orderer1.ca.com

orderers:
  orderer1.ca.com:
    url: localhost:7050
    # url: orderer1.ca.com:7050
    grpcOptions:
      ssl-target-name-override: orderer1.ca.com
    tlsCACerts:
      # Certificate location absolute path
      # path: D:\Resource Files\root\fabric-samples\test-network\organizations\ordererOrganizations\example.com\tlsca\tlsca.example.com-cert.pem
      path: /home/wayne/samba/bs_server/fabric/organizations/ordererOrganizations/ca.com/msp/tlscacerts/tlsca.ca.com-cert.pem

client:
  organization: Org1
  logging:
    level: info
  cryptoconfig:
    # path: D:\Resource Files\root\fabric-samples\test-network\organizations
    path: /home/wayne/samba/bs_server/fabric/organizations
  credentialStore:
    path: "/tmp/state-store"
    cryptoStore:
      path: /tmp/msp
  tlsCerts:
    client:
      key:
        # path: D:\Resource Files\root\fabric-samples\test-network\organizations\peerOrganizations\org1.example.com\users\User1@org1.example.com\tls\client.key
        path: /home/wayne/samba/bs_server/fabric/organizations/peerOrganizations/org1.ca.com/users/Admin@org1.ca.com/msp/keystore/priv_sk
      cert:
        # path: D:\Resource Files\root\fabric-samples\test-network\organizations\peerOrganizations\org1.example.com\users\User1@org1.example.com\tls\client.crt
        path: /home/wayne/samba/bs_server/fabric/organizations/peerOrganizations/org1.ca.com/users/Admin@org1.ca.com/msp/signcerts/cert.pem

organizations:
  Org1:
    mspid: Org1MSP
    # cryptoPath: D:\Resource Files\root\fabric-samples\test-network\organizations\peerOrganizations\org1.example.com\users\{username}@org1.example.com\msp
    cryptoPath: /home/wayne/samba/bs_server/fabric/organizations/peerOrganizations/org1.ca.com/users/{username}@org1.ca.com/msp
    peers:
      - peer0.org1.ca.com
    users:
      User1:
        certs:
          path: /home/wayne/samba/bs_server/fabric/organizations/peerOrganizations/org1.ca.com/users/Admin@org1.ca.com/msp/signcerts/cert.pem
        key:
          path: /home/wayne/samba/bs_server/fabric/organizations/peerOrganizations/org1.ca.com/users/Admin@org1.ca.com/msp/keystore/priv_sk
peers:
  peer0.org1.ca.com:
    # url: peer0.org1.ca.com:7051
    url: localhost:7051
    tlsCACerts:
      # path: D:\Resource Files\root\fabric-samples\test-network\organizations\peerOrganizations\org1.example.com\tlsca\tlsca.org1.example.com-cert.pem
        path: /home/wayne/samba/bs_server/fabric/organizations/peerOrganizations/org1.ca.com/tlsca/tlsca.org1.ca.com-cert.pem
